"""
ASE (hapmixQTL) validation harness -- tiered.

The existing hapmixQTL test suite (tests/test_hapmixqtl.py, ~35 tests) is almost
entirely INTERNAL CONSISTENCY ("does the code compute the formula we wrote") plus
"can it recover a planted causal variant". Neither kind of test can detect an
invalid error rate. This harness supplies the missing evidence.

Three structural facts about the implementation motivate the design:

  F1 (tau).  `tau_mode='zero'` WAS the default in map_nominal/map_cis when this
      harness was written (it is 'estimate' now, because of Tier 0), so the
      weights are w_i = 1/v_inf_i. Combined with the known-variance GLS SE
      (Var(beta) = 1/xx, no estimated dispersion), the model asserts that Gibbs
      inferential variance is the ONLY source of error variance. Any additional
      biological variance is unmodelled -> SE too small -> anticonservative.

  F2 (Cat).  compute_summaries_from_gibbs returns the a-t inferential covariance
      and read_hapmixqtl_inputs accepts a cat_bed, but calculate_hapmixqtl_nominal
      combines the two channels by SCALAR inverse-variance meta-analysis, which
      assumes independence. a and t are both functions of the same Gibbs draws,
      so Cov != 0 in general and the combined SE is missing a 2*w_a*w_t*Cov term.
      Tier 0b MEASURED this and retired it: the slope estimators are uncorrelated
      even at rho = 0.9, because s is orthogonal to g/2 under random phase, so
      ignoring Cat is correct (hapmixqtl.py module docstring).

  F3 (dof). p-values are computed with get_t_pval(tstat, N-2-n_cov), i.e. a
      t-reference for what is by construction a known-variance z-statistic. Minor
      and conservative at large N; included here only so it is not confounded in.

Tiers
-----
  Tier 0  Null calibration. Factorial sweep over (biological variance, a-t
          inferential correlation) x (tau_mode). Reports realized type-I error at
          alpha = 0.05 / 0.01 / 1e-3, KS uniformity, lambda_GC. The cell with
          bio=0, rho=0 is the CONTROL where the model is exactly true; it must
          be nominal or the harness itself is wrong.
  Tier 1  CI coverage of a known log aFC (the sharpest probe of whether the
          inferential uncertainty propagates into beta_se correctly).
  Tier 2  Power vs total-only at MATCHED EMPIRICAL type-I error (not a matched
          nominal threshold -- an anticonservative method always "wins" on
          nominal, so that comparison is meaningless).
  Tier 3  Semisynthetic: simulate allele-level counts -> Gibbs draws ->
          compute_summaries_from_gibbs, so Va/Vt/Cat and the kappa pseudocount
          behaviour are generated by the real code path rather than assumed.

Run:  python tests/ase_validation.py --out results.json
"""

import argparse
import json
import sys
import numpy as np
import torch
from pathlib import Path

sys.path.insert(0, str(Path(__file__).parent.parent))

from scipy import stats

try:
    from tensorqtl.hapmixqtl import (
        WeightedResidualizer, _estimate_tau,
        calculate_hapmixqtl_nominal, compute_summaries_from_gibbs)
except ImportError:  # standalone: tensorqtl dir directly on path
    sys.path.insert(0, str(Path(__file__).parent.parent / 'tensorqtl'))
    from hapmixqtl import (
        WeightedResidualizer, _estimate_tau,
        calculate_hapmixqtl_nominal, compute_summaries_from_gibbs)

DTYPE = torch.float64


# ---------------------------------------------------------------------------
#  Core simulator
# ---------------------------------------------------------------------------

def simulate_channels(N, V, rng, beta=0.0, maf=0.35,
                      v_inf_lo=0.05, v_inf_hi=0.30,
                      sigma_bio=0.0, rho_at=0.0):
    """
    Simulate one dataset (one gene, V cis variants, N samples).

    The generative model is exactly the one hapmixQTL assumes, EXCEPT for two
    deliberately controllable violations:

      sigma_bio : extra biological (non-inferential) error SD added to BOTH
                  channels. sigma_bio=0 => the known-variance model is exactly
                  true (w = 1/v_inf is the correct precision).
      rho_at    : correlation between the ASE and total INFERENTIAL noise, i.e.
                  the thing Cat measures. rho_at=0 => channels independent.

    Returns genotypes [V,N], sign [V,N], a [N], t [N], va [N], vt [N].
    The causal variant (if beta != 0) is index 0.
    """
    g = rng.binomial(2, maf, size=(V, N)).astype(np.float64)
    # signed het indicator s = xL - xR (random phase for hets)
    sign = np.zeros((V, N))
    het = g == 1
    sign[het] = rng.choice([-1.0, 1.0], size=int(het.sum()))

    va = rng.uniform(v_inf_lo, v_inf_hi, N)
    vt = rng.uniform(v_inf_lo, v_inf_hi, N)

    # correlated inferential noise -> induces Cat = rho * sqrt(va*vt)
    z = rng.multivariate_normal([0, 0], [[1.0, rho_at], [rho_at, 1.0]], size=N)
    a = np.sqrt(va) * z[:, 0]
    t = 2.0 + np.sqrt(vt) * z[:, 1]

    # extra biological variance (unmodelled when tau_mode='zero')
    if sigma_bio > 0:
        a = a + rng.normal(0, sigma_bio, N)
        t = t + rng.normal(0, sigma_bio, N)

    # planted signal on variant 0, on the SAME log-aFC scale in both channels
    if beta != 0.0:
        a = a + beta * sign[0]
        t = t + beta * (g[0] / 2.0)

    return g, sign, a, t, va, vt


def run_association(g, sign, a, t, va, vt, tau_mode='zero', covariates=None):
    """Drive the production statistic. Returns (tstat, slope, se, slope_t, se_t)."""
    dev = 'cpu'
    g_t = torch.tensor(g, dtype=DTYPE, device=dev)
    s_t = torch.tensor(sign, dtype=DTYPE, device=dev)
    a_t = torch.tensor(a, dtype=DTYPE, device=dev)
    t_t = torch.tensor(t, dtype=DTYPE, device=dev)
    va_t = torch.tensor(va, dtype=DTYPE, device=dev).clamp(min=1e-8)
    vt_t = torch.tensor(vt, dtype=DTYPE, device=dev).clamp(min=1e-8)
    cov_t = None if covariates is None else torch.tensor(covariates, dtype=DTYPE, device=dev)

    if tau_mode == 'estimate':
        tau_a = _estimate_tau(a_t, va_t, cov_t, dev)
        tau_t = _estimate_tau(t_t, vt_t, cov_t, dev)
        sqrt_wa = torch.sqrt(1.0 / (va_t + tau_a))
        sqrt_wt = torch.sqrt(1.0 / (vt_t + tau_t))
    else:
        sqrt_wa = torch.sqrt(1.0 / va_t)
        sqrt_wt = torch.sqrt(1.0 / vt_t)

    res_a = WeightedResidualizer(cov_t, sqrt_wa)
    res_t = WeightedResidualizer(cov_t, sqrt_wt)
    tstat, slope, se, slope_a, se_a, slope_tc, se_tc = calculate_hapmixqtl_nominal(
        g_t, s_t, a_t, t_t, sqrt_wa, sqrt_wt, res_a, res_t)
    return (tstat.numpy(), slope.numpy(), se.numpy(),
            slope_tc.numpy(), se_tc.numpy(), slope_a.numpy(), se_a.numpy())


def pvals_from_t(tstat, N, n_cov=0):
    """Match the production path: get_t_pval(tstat, dof=N-2-n_cov)."""
    dof = N - 2 - n_cov
    return 2 * stats.t.sf(np.abs(tstat), dof)


# ---------------------------------------------------------------------------
#  Tier 0 -- null calibration
# ---------------------------------------------------------------------------

def _calib_metrics(p, alphas=(0.05, 0.01, 1e-3)):
    p = np.asarray(p)
    p = p[np.isfinite(p)]
    out = {'n': int(p.size)}
    for al in alphas:
        k = int((p < al).sum())
        rate = k / p.size
        # binomial SE of the realized rate
        se = np.sqrt(max(rate, 1e-12) * (1 - rate) / p.size)
        out[f'typeI_{al:g}'] = float(rate)
        out[f'typeI_{al:g}_ratio'] = float(rate / al)
        out[f'typeI_{al:g}_se'] = float(se)
    out['ks_p'] = float(stats.kstest(p, 'uniform').pvalue)
    # genomic inflation factor from the chi2(1) median
    chi2 = stats.chi2.isf(p, 1)
    out['lambda_gc'] = float(np.median(chi2) / stats.chi2.ppf(0.5, 1))
    return out


def tier0_null_calibration(reps=400, N=200, V=20, seed=0,
                           sigma_bio_grid=(0.0, 0.3, 0.6),
                           rho_grid=(0.0, 0.5, 0.9),
                           tau_modes=('zero', 'estimate')):
    """Factorial null calibration sweep. All variants are null (beta=0)."""
    results = []
    for tau_mode in tau_modes:
        for sb in sigma_bio_grid:
            for rho in rho_grid:
                P, Pt = [], []
                for r in range(reps):
                    rng = np.random.RandomState(seed + 100000 * int(sb * 10)
                                                + 1000 * int(rho * 10) + r)
                    g, s, a, t, va, vt = simulate_channels(
                        N, V, rng, beta=0.0, sigma_bio=sb, rho_at=rho)
                    ts, _, _, st, se_t, _, _ = run_association(
                        g, s, a, t, va, vt, tau_mode=tau_mode)
                    P.append(pvals_from_t(ts, N))
                    with np.errstate(divide='ignore', invalid='ignore'):
                        Pt.append(pvals_from_t(st / se_t, N))
                m = _calib_metrics(np.concatenate(P))
                mt = _calib_metrics(np.concatenate(Pt))
                results.append({'tau_mode': tau_mode, 'sigma_bio': sb,
                                'rho_at': rho, 'combined': m, 'total_only': mt})
                print(f"  tau={tau_mode:8s} bio={sb:.1f} rho={rho:.1f} | "
                      f"typeI@0.05={m['typeI_0.05']:.4f} "
                      f"({m['typeI_0.05_ratio']:.2f}x)  "
                      f"@0.001={m['typeI_0.001']:.5f} "
                      f"({m['typeI_0.001_ratio']:.2f}x)  "
                      f"lambda={m['lambda_gc']:.2f}", flush=True)
    return results


# ---------------------------------------------------------------------------
#  Tier 0b -- DIRECT test of the channel-independence assumption
# ---------------------------------------------------------------------------

def tier0b_channel_correlation(reps=1500, N=200, seed=555,
                               rho_grid=(0.0, 0.5, 0.9), sigma_bio=0.0):
    """
    Measure corr(beta_ASE, beta_total) under the null across replicates.

    This is the EXACT quantity the scalar inverse-variance meta-analysis assumes
    is zero (F2). Inferring it from type-I error is indirect; this measures it.

    Prediction if the assumption is safe: even when the underlying a-t
    inferential noise is strongly correlated (rho_at -> 0.9), the two SLOPE
    estimators stay uncorrelated, because the ASE predictor s (signed het
    indicator, random phase) is orthogonal to the total predictor g/2:
    E[s | g=1] = 0 under random phase.
    """
    results = []
    for rho in rho_grid:
        ba, bt, corr_pred = [], [], []
        for r in range(reps):
            rng = np.random.RandomState(seed + r + 977 * int(rho * 10))
            g, s, a, t, va, vt = simulate_channels(
                N, 1, rng, beta=0.0, sigma_bio=sigma_bio, rho_at=rho)
            _, _, _, st, se_t, sa, se_a = run_association(
                g, s, a, t, va, vt, tau_mode='zero')
            if np.isfinite(se_a[0]) and np.isfinite(se_t[0]):
                ba.append(float(sa[0])); bt.append(float(st[0]))
                # empirical predictor orthogonality for this replicate
                sw = 1.0 / va
                corr_pred.append(float(np.corrcoef(s[0], g[0] / 2.0)[0, 1]))
        ba, bt = np.array(ba), np.array(bt)
        r_hat = float(np.corrcoef(ba, bt)[0, 1])
        # Fisher z 95% CI for the correlation
        n = len(ba)
        z = np.arctanh(r_hat); sez = 1 / np.sqrt(max(n - 3, 1))
        lo, hi = np.tanh(z - 1.96 * sez), np.tanh(z + 1.96 * sez)
        results.append({'rho_at': rho, 'n': n,
                        'corr_beta_a_beta_t': r_hat,
                        'ci_lo': float(lo), 'ci_hi': float(hi),
                        'mean_corr_predictors': float(np.nanmean(corr_pred))})
        print(f"  rho_at={rho:.1f} | corr(beta_a,beta_t)={r_hat:+.4f} "
              f"[{lo:+.3f},{hi:+.3f}]  corr(s,g/2)={np.nanmean(corr_pred):+.4f}",
              flush=True)
    return results


# ---------------------------------------------------------------------------
#  Tier 1 -- CI coverage
# ---------------------------------------------------------------------------

def tier1_coverage(reps=400, N=200, seed=1234, beta=0.5,
                   sigma_bio_grid=(0.0, 0.3, 0.6),
                   rho_grid=(0.0, 0.5),
                   tau_modes=('zero', 'estimate')):
    """95% CI coverage of the true log aFC on the causal variant."""
    results = []
    for tau_mode in tau_modes:
        for sb in sigma_bio_grid:
            for rho in rho_grid:
                cov, bias, widths = [], [], []
                for r in range(reps):
                    rng = np.random.RandomState(seed + 7919 * r
                                                + 131 * int(sb * 10) + int(rho * 10))
                    g, s, a, t, va, vt = simulate_channels(
                        N, 1, rng, beta=beta, sigma_bio=sb, rho_at=rho)
                    _, slope, se, _, _, _, _ = run_association(
                        g, s, a, t, va, vt, tau_mode=tau_mode)
                    b, e = float(slope[0]), float(se[0])
                    if not np.isfinite(e):
                        continue
                    lo, hi = b - 1.96 * e, b + 1.96 * e
                    cov.append(lo <= beta <= hi)
                    bias.append(b - beta)
                    widths.append(2 * 1.96 * e)
                results.append({
                    'tau_mode': tau_mode, 'sigma_bio': sb, 'rho_at': rho,
                    'coverage': float(np.mean(cov)), 'n': int(len(cov)),
                    'bias': float(np.mean(bias)),
                    'mean_ci_width': float(np.mean(widths)),
                    'empirical_sd': float(np.std([b + beta for b in bias])),
                })
                print(f"  tau={tau_mode:8s} bio={sb:.1f} rho={rho:.1f} | "
                      f"coverage={results[-1]['coverage']:.3f} (target 0.95)  "
                      f"bias={results[-1]['bias']:+.4f}", flush=True)
    return results


# ---------------------------------------------------------------------------
#  Tier 2 -- power at MATCHED empirical type-I error
# ---------------------------------------------------------------------------

def tier2_power(reps=400, N=200, seed=99, beta=0.4, alpha=0.05,
                maf_grid=(0.15, 0.35), sigma_bio=0.3, tau_mode='estimate'):
    """
    Calibrate each method's threshold on its OWN null distribution, then compare
    power at that matched empirical type-I error. This is the only fair
    comparison when one method may be anticonservative.
    """
    results = []
    for maf in maf_grid:
        null_c, null_t = [], []
        for r in range(reps):
            rng = np.random.RandomState(seed + r)
            g, s, a, t, va, vt = simulate_channels(
                N, 1, rng, beta=0.0, maf=maf, sigma_bio=sigma_bio)
            ts, _, _, st, se_t, _, _ = run_association(g, s, a, t, va, vt, tau_mode=tau_mode)
            null_c.append(abs(float(ts[0])))
            null_t.append(abs(float(st[0] / se_t[0])) if np.isfinite(se_t[0]) else 0.0)
        thr_c = np.quantile([x for x in null_c if np.isfinite(x)], 1 - alpha)
        thr_t = np.quantile([x for x in null_t if np.isfinite(x)], 1 - alpha)

        hit_c, hit_t = [], []
        for r in range(reps):
            rng = np.random.RandomState(seed + 500000 + r)
            g, s, a, t, va, vt = simulate_channels(
                N, 1, rng, beta=beta, maf=maf, sigma_bio=sigma_bio)
            ts, _, _, st, se_t, _, _ = run_association(g, s, a, t, va, vt, tau_mode=tau_mode)
            hit_c.append(abs(float(ts[0])) > thr_c)
            hit_t.append((abs(float(st[0] / se_t[0])) > thr_t)
                         if np.isfinite(se_t[0]) else False)
        results.append({'maf': maf, 'alpha': alpha, 'beta': beta,
                        'thr_combined': float(thr_c), 'thr_total': float(thr_t),
                        'power_combined': float(np.mean(hit_c)),
                        'power_total_only': float(np.mean(hit_t))})
        print(f"  maf={maf:.2f} | power combined={results[-1]['power_combined']:.3f}  "
              f"total-only={results[-1]['power_total_only']:.3f}  "
              f"(matched empirical alpha={alpha})", flush=True)
    return results


# ---------------------------------------------------------------------------
#  Tier 3 -- semisynthetic: counts -> Gibbs draws -> real summary code path
# ---------------------------------------------------------------------------

def simulate_gibbs_counts(N, rng, depth=50, n_draws=100, beta=0.0, maf=0.35,
                          disp=0.1, kappa=0.5):
    """
    Allele-level count simulation feeding the REAL compute_summaries_from_gibbs.

    yL, yR are haplotype counts ~ NB(mean, disp). A Gibbs posterior is emulated
    by multinomial resampling of the observed total at each draw, which is what
    a quantifier's posterior over allelic assignment looks like. Va, Vt, Cat and
    all kappa-pseudocount behaviour are then produced by the production code.
    """
    g = rng.binomial(2, maf, size=(1, N)).astype(np.float64)
    sign = np.zeros((1, N))
    het = g[0] == 1
    sign[0, het] = rng.choice([-1.0, 1.0], size=int(het.sum()))

    # true per-haplotype means; ASE only expressed in hets
    muL = np.full(N, depth / 2.0)
    muR = np.full(N, depth / 2.0)
    if beta != 0.0:
        fold = np.exp(beta * sign[0] / 2.0)
        muL = muL * fold
        muR = muR / np.clip(fold, 1e-8, None)

    def nb(mu):
        if disp <= 0:
            return rng.poisson(mu)
        r = 1.0 / disp
        p = r / (r + mu)
        return rng.negative_binomial(r, p)

    yL_obs = nb(muL).astype(float)
    yR_obs = nb(muR).astype(float)
    tot = yL_obs + yR_obs

    # emulate the quantifier posterior: multinomial split of the observed total
    frac = (yL_obs + kappa) / (tot + 2 * kappa)
    yL = np.empty((1, N, n_draws))
    yR = np.empty((1, N, n_draws))
    for i in range(N):
        d = rng.binomial(int(tot[i]), frac[i], size=n_draws).astype(float)
        yL[0, i, :] = d
        yR[0, i, :] = tot[i] - d
    return g, sign, yL, yR


def tier3_semisynthetic(reps=300, N=200, seed=2024, depth_grid=(20, 100),
                        tau_modes=('zero', 'estimate')):
    """Null calibration on summaries produced by the real Gibbs summary code."""
    results = []
    for tau_mode in tau_modes:
        for depth in depth_grid:
            P, cats = [], []
            for r in range(reps):
                rng = np.random.RandomState(seed + 31 * r + depth)
                g, sign, yL, yR = simulate_gibbs_counts(
                    N, rng, depth=depth, beta=0.0)
                A, T, Va, Vt, Cat = compute_summaries_from_gibbs(yL, yR)
                a, t = A[0], T[0]
                va, vt = Va[0], Vt[0]
                # observed inferential correlation actually induced by the data
                denom = np.sqrt(np.clip(va, 1e-12, None) * np.clip(vt, 1e-12, None))
                cats.append(np.mean(Cat[0] / denom))
                ts, _, _, _, _, _, _ = run_association(
                    g, sign, a, t, va, vt, tau_mode=tau_mode)
                P.append(pvals_from_t(ts, N))
            m = _calib_metrics(np.concatenate(P))
            results.append({'tau_mode': tau_mode, 'depth': depth,
                            'mean_inferential_corr_at': float(np.mean(cats)),
                            'combined': m})
            print(f"  tau={tau_mode:8s} depth={depth:3d} | "
                  f"typeI@0.05={m['typeI_0.05']:.4f} ({m['typeI_0.05_ratio']:.2f}x)  "
                  f"lambda={m['lambda_gc']:.2f}  "
                  f"corr(a,t)={np.mean(cats):+.3f}", flush=True)
    return results


# ---------------------------------------------------------------------------

def main():
    ap = argparse.ArgumentParser()
    ap.add_argument('--reps', type=int, default=400)
    ap.add_argument('--N', type=int, default=200)
    ap.add_argument('--out', type=str, default=None)
    ap.add_argument('--tiers', type=str, default='0,1,2,3')
    args = ap.parse_args()
    tiers = set(args.tiers.split(','))
    out = {'config': {'reps': args.reps, 'N': args.N}}

    if '0' in tiers:
        print("\n=== TIER 0: null calibration (factorial) ===")
        out['tier0'] = tier0_null_calibration(reps=args.reps, N=args.N)
        print("\n=== TIER 0b: direct test of channel independence (Cat) ===")
        out['tier0b'] = tier0b_channel_correlation(reps=max(args.reps, 1000), N=args.N)
    if '1' in tiers:
        print("\n=== TIER 1: CI coverage of known log aFC ===")
        out['tier1'] = tier1_coverage(reps=args.reps, N=args.N)
    if '2' in tiers:
        print("\n=== TIER 2: power at matched empirical type-I error ===")
        out['tier2'] = tier2_power(reps=args.reps, N=args.N)
    if '3' in tiers:
        print("\n=== TIER 3: semisynthetic (counts -> Gibbs -> real summaries) ===")
        out['tier3'] = tier3_semisynthetic(reps=min(args.reps, 300), N=args.N)

    if args.out:
        Path(args.out).write_text(json.dumps(out, indent=2))
        print(f"\nwrote {args.out}")
    return out


if __name__ == '__main__':
    main()
